### PR TITLE
Add support for Visual Studio 15

### PR DESCRIPTION
**Pull request by Bobo1239**
(Also reorder for consistency)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by MSleepyPanda** [comment]
I have VS Community 2015, Update 2 and on my System there is no Version 15 of MSBuild. Either i do not have the correct VS 2015, or this criterion doesn't apply.

In case i do not have the correct VS2015, how would i obtain the correct one? Reinstall?

Sceenshots for Clarification:
Excempt from Regedit:
regedit
Screenshot from VS C2015
vs_2015

**Comment by Bobo1239** [comment]
VS 15 (Preview atm) is not VS 2015 ([Wiki](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#2015)). VS 2015 should already be covered by [`"14.0" => "Visual Studio 14 2015"`](https://github.com/Bobo1239/cmake-rs/blob/27f170f7c5ccf6e621b1f82240a9a06c06626571/src/lib.rs#L387).

Are you running in a command prompt which has a correctly configured `PATH` environment variable? (e.g. by running `vcvars64.bat` in `{VS_INSTALLATION_PATH}\Common7\IDE\VisualCpp\Auxiliary\Build` or similar)

**Comment by Arnavion** [comment]
Perhaps it was different in the preview builds of VS2017, but atleast in the RTM version of the Community edition the MSBuild version is still 14.0. I'm having to set the `VisualStudioVersion` env var to override the generator so that cmake-using crates like libssh2-sys can build with VS2017 instead of complaining that they can't find VS2015.

**Comment by Bobo1239** [comment]
I can check in about 12h when I have access to my Windows machine again.

**Comment by Bobo1239** [comment]
Hm, pretty sure that at least my VS2017 CE installation has MSBuild 15.x.
```
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools>vsdevcmd
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26228.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools>msbuild
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.
```
also:
```
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0
```
I did upgrade from the preview builds though so I'm not certain if it's different when doing a clean install (would be weird IMO).

**Comment by Arnavion** [comment]
I have the same output and also that directory, but no corresponding reg key.

**Comment by Bobo1239** [comment]
Hm, I neither have a key for 15.0 nor for 14.0...
(assuming `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions` is the right place to look for)

Unfortunately I'm not really knowledgeable about this stuff as I'm a MinGW user. (And I currently can't compile anything with the MSVC toolchain due to linking problems. (`msvcrt.lib(chkstk.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'`))

Sorry, somebody else will have to look into this.

**Pull request merged**
