### PR TITLE
Add support for the CMAKE environmental variable

### PR DESCRIPTION
**Pull request by marmistrz**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Is the precedent for doing somethign like this?

**Comment by marmistrz** [comment]
Yes, without this PR it's impossible to compile Servo on CentOS, since `cmake` is CMake 2.x, `cmake3` is CMake 3.x

**Comment by alexcrichton** [comment]
Could this perhaps automatically detect that and not require use of the env var? Do other projects use CMAKE?

**Comment by marmistrz** [comment]
I don't think it's a good idea. For example, in Arch you can install cmake 2.x to /usr/bin/cmake-2 and it may be useful to fall back to cmake 2 if there are some compatibility issues with cmake 3.

**Comment by alexcrichton** [comment]
Is the `CMAKE` env var standard in any other systems? I'd be somewhat wary of creating a "new standard" in a sense...

**Comment by marmistrz** [comment]
I have never seen anything like this, probably because cmake is usually run manually, where one can specify the path himself.
If you have an idea for a better variable, let me know.

**Comment by alexcrichton** [comment]
Ok sounds like we should go with this as is then, so I'll merge! Maybe we can now be trendsetters :)

**Comment by marmistrz** [comment]
The rusty avant-garde! :)
My plan for now:
1. Bump the version to include this change
2. Bump the `cmake-rs` dependency in `gecko-media` to allow build on CentOS
3. Edit the servo `README` with extra instructions how to build on CentOS.

Is it feasible? Should I just make a PR to this repo bumping the version?

**Comment by alexcrichton** [comment]
Sounds reasonable! Nah it's ok I'll go ahead and do the bump

**Pull request merged**
