### PR TITLE
Honor the CMAKE_GENERATOR environment variable

### PR DESCRIPTION
**Pull request by roblabla**
Should hopefully help cross-compiling crates using cmake-rs from Linux to Windows.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! To confirm, are there other tools that respect this env var?

**Comment by roblabla** [comment]
cmake itself does. See https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html

**Comment by alexcrichton** [comment]
Ok great! I think this needs a rustfmt and afterwards is good to go.

**Comment by roblabla** [comment]
fmt fixed!

**Pull request merged**
