### PR TITLE
Updates to visual studio generator selection

### PR DESCRIPTION
**Pull request by photex**
Howdy!

Per the discussion in #12 I'm proposing the following update.

I'm happy to make any changes and corrections.

### CODE REVIEW

**Comment by photex** [comment]
Hrm... wait a sec... this worked fine and then it didn't.

I got some strange juju trying to build later and I'm trying to triage what on earth the change could possibly have been because all things considered the determination was working as expected. O.o

**Comment by photex** [comment]
Building with 0.1.17 from crates.io works if I specify the generator manually. Building from path or from git fails with:

Build output:

```
error: failed to run custom build command for `nanomsg-sys v0.7.0 (file:///C:/projects/nanomsg.rs/nanomsg_sys)`
Process didn't exit successfully: `C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "\\\\?\\C:\\projects\\nanomsg.rs\\nanomsg_sys\\nanomsg" "-G" "Visual Studio 14 2015 Win64" "-DNN_STATIC_LIB=ON" "-DNN_ENABLE_DOC=OFF" "-DNN_TESTS=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\projects\\nanomsg.rs\\target\\debug\\build\\nanomsg-sys-94fa98c2d827f080\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_BUILD_TYPE=Release"
-- The C compiler identification is MSVC 19.0.23918.0
-- Check for working C compiler using: Visual Studio 14 2015 Win64
-- Check for working C compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detected nanomsg ABI v5.0.0
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Looking for InitializeConditionVariable
-- Looking for InitializeConditionVariable - found
-- Performing Test NN_HAVE_GCC_ATOMIC_BUILTINS
-- Performing Test NN_HAVE_GCC_ATOMIC_BUILTINS - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: C:/projects/nanomsg.rs/target/debug/build/nanomsg-sys-94fa98c2d827f080/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 7/18/2016 6:47:44 PM.
Project "C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\install.vcxproj" on node 1 (default targets).
Project "C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\install.vcxproj" (1) is building "C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Release\ZERO_CHECK\".
  Creating directory "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6001: Invalid command line switch for "cmd.exe". Illegal characters in path. [C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\ZERO_CHECK.vcxproj]
Done Building Project "C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\ZERO_CHECK.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\install.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\install.vcxproj" (default target) (1) ->
"C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\ZERO_CHECK.vcxproj" (default target) (2) ->
(CustomBuild target) -> 
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6001: Invalid command line switch for "cmd.exe". Illegal characters in path. [C:\projects\nanomsg.rs\target\debug\build\nanomsg-sys-94fa98c2d827f080\out\build\ZERO_CHECK.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.61

--- stderr
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE
    CMAKE_CXX_FLAGS


thread '<main>' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', c:/Users/phote/.cargo\git\checkouts\cmake-rs-79f579515df22732\master\src\lib.rs:496
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Tried this using both alexcrichton/cmake-rs as well as my fork at photex/cmake-rs.

**Comment by photex** [comment]
Ah well, looks like I'm getting bit by this https://github.com/alexcrichton/cmake-rs/commit/ca0989c5dd9d191d7d5811851b41a72be64fc925

Reverting that commit things work fine again for me.

**Comment by alexcrichton** [comment]
Thanks for the PR! Perhaps this could vendor some windows registry code like gcc-rs does to avoid relying on executing an external command?

**Comment by photex** [comment]
I'd be happy to do that. I honestly started doing that but wasn't sure if this was better. Meanwhile, some parts of gcc-rs that I could start with weren't public and I didn't want to also rope that in.
If it's all the same to you I'll just use the win32 api directly then.

**Comment by alexcrichton** [comment]
@photex if you copy [this file](https://github.com/alexcrichton/gcc-rs/blob/master/src/registry.rs) and then ensure it only compiles on Windows, that should provide all we need I believe.

**Comment by photex** [comment]
Since I wasn't able to use cmake-rs at all from git due to a previously merged commit I included a fix in this commit. I'm happy to roll that into a separate PR though. It seems to only have broken builds on windows. 
I moved the canonicalization of the path into the function referenced by the comment. 

I was able to build my fork of nanomsg.rs using a developer shell as well as a vanilla shell.

**Comment by alexcrichton** [comment]
Awesome, looks great to me, thanks!

**Pull request merged**
