### PR TITLE
Add opt_level configuration method

### PR DESCRIPTION
**Pull request by devcen13**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! This is somewhat worrisome to me now that I think about it though... 

So the intention here is to learn about the flags that we need to pass to the C compiler to get situations like cross-compilation to work. We don't actually want to pick up an optimization level flag here so it in theory shouldn't matter. I believe the idiomatic way to do opt/debug compiles with cmake is through the usage of `-DCMAKE_BUILD_TYPE`.

Now it may be the case, however, that these cflags we pick up *override* the optimization level set by `CMAKE_BUILD_TYPE`, which would be very bad! I know that in the compiler we [do something similar](https://github.com/rust-lang/rust/blob/371bf0eda20eed78d5ed366426acd167b0d15b2e/src/bootstrap/build/mod.rs#L809) by filtering out the optimization flag, and it may be the case that we need to do that here as well.

**Comment by devcen13** [comment]
Thanks for your feedback.
I have to mention that at the moment we have a hardcoded optimization level flag `-O0` regardless of the build type and it does override the optimization level set by `CMAKE_BUILD_TYPE`.
Maybe the better aproach here would be removing the `gcc::Config::opt_level` call.
This way, in general case the optimization level would be set through the `-DCMAKE_BUILD_TYPE` option. And in some unusual case when explicit specifying the opt_level is required, one can do this using the `OPT_LEVEL` env variable.

**Comment by alexcrichton** [comment]
Hm so actually I think the best bet would be to modify gcc-rs directly to just omit this from when we learn about the flags. It seems like it's basically always wrong and causes more problems than it should (or at least provide an option to turn this off).

If we just remove the call to `opt_level` then it'll still try to infer an opt-level and thread it through, really this wants a `opt_level(None)` call I think.

**Comment by gnzlbg** [comment]
Does this interact with https://github.com/alexcrichton/cmake-rs/pull/52 ? It changes how the `CMAKE_BUILD_TYPE` is actually determined.

**Pull request closed without merging**
