### PR TITLE
Clean up Visual Studio version determination

### PR DESCRIPTION
**Pull request by tomaka**
Instead of parsing the installation path, we invoke `link.exe` and see which version it returns.

Successfully works with Visual Studio 12. I didn't test VS 14 but its link.exe also returns the correct version.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Out of curiosity, did you run into this? I'm curious what the environment looked like to trigger this

**Comment by tomaka** [comment]
The current code assumes that you install Visual Studio in the default path, but I installed it in a directory simply named `VisualStudio` instead.

**Comment by alexcrichton** [comment]
Ok sounds good to me, thanks!

**Comment by alexcrichton** [comment]
Unfortunately I had to [revert this](https://github.com/alexcrichton/cmake-rs/commit/3b918977f89b5c52228f46f16e3257a65971f298) as it caused [a regression](https://ci.appveyor.com/project/alexcrichton/ssh2-rs/build/1.0.505/job/5fop4x19m9ewouio) which apparently because it was [running `/usr/bin/link.exe`](https://ci.appveyor.com/project/alexcrichton/ssh2-rs/build/1.0.508/job/d364k31di1orek8x) instead of MSVC's link.exe.

I'm also not sure that the `link.exe` version printed corresponds to the MSVC version? For example the version printed through `cl.exe` is 19...

**Comment by tomaka** [comment]
> I'm also not sure that the link.exe version printed corresponds to the MSVC version? For example the version printed through cl.exe is 19...

That was determine empirically. The code currently only supports VS 12 and 14, and the link.exe of both VS 12 and 14 return the correct version. Maybe that's not the case for other versions of MSVC, but the person who will add support for another version will notice if it doesn't work.

**Comment by alexcrichton** [comment]
Ah yeah that's a good point, sounds good to me! If there's a solution to choosing the wrong `link.exe` by accident I'd be fine relanding

**Pull request merged**
