### PR TITLE
Add methods to pass arguments to CMake

### PR DESCRIPTION
**Pull request by lilianmoraru**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder if actually these should be called `cmake_build_args` as they're only passed to the build step? (along with docs explaining that)

**Comment by lilianmoraru** [comment]
I am okay with whatever you think the API should look like.
My worry with this renaming would be that it might be confusing because there is also `build_arg`.

Note that the example I gave with `-C` is run in CMake's generation step.
Most flags CMake accepts are run in the generation step(even things like `--trace`).
Or I might be confusing what you mean by build step?

**Comment by alexcrichton** [comment]
Ah yeah we invoke cmake twice here, but this is only applying to the build step? In that sense would this not solve your use case of passing `-C` to the generation step?

I'd be fine adding two suites of methods, one for the build step and one for the generation step. We should just be clear what arguments are going where.

**Comment by lilianmoraru** [comment]
If I run "-C" using `build_arg`, I get an error.
From what I know, `-- [flags]` are passed to the native build tool, not to CMake's generation step and that's why passing `-C` to `build_arg` doesn't work.

**Comment by alexcrichton** [comment]
These just go before `--`, right?

**Comment by lilianmoraru** [comment]
Yes.
You can see the `--` separator here: https://github.com/alexcrichton/cmake-rs/pull/29/files#diff-b4aea3e418ccdb71239b96952d9cddb6R493

**Comment by alexcrichton** [comment]
Hm ok so to take a step back I'm proposing two new methods:

* `cmake_config_arg`
* `cmake_build_arg`

The former appends arguments to the configuration cmake command, where the latter appends arguments to the build command (but before `--` where after which other build arguments come into play)

Does that make sense?

**Pull request closed without merging**
