### PR TITLE
Use CARGO_MAKEFLAGS on !Windows to make use of Cargo's jobserver

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could this perhaps be forwarded through as the `MAKEFLAGS` env var rather than arguments? (I think that's how it's typically communicated?)

**Comment by nox** [comment]
That's what I intended to do, but I'm not sure how that interacts with cmake (given that's what we invoke, not make directly).

**Comment by alexcrichton** [comment]
Env vars are inherited, so I think it'd work? Mind testing?

**Comment by nox** [comment]
Google says it should work just fine. Let me amend.

**Comment by nox** [comment]
@alexcrichton I amended the code, btw.

**Comment by alexcrichton** [comment]
Oh can this avoid the use of `env::set_var` and set the environment variable directly on the command being spawned?

**Comment by nox** [comment]
I will do that.

@alexcrichton IMO everything else related to parallel building should be removed (e.g. support for Visual Studio etc), this stuff kills computers if multiple build scripts all start 8 jobs.

**Comment by alexcrichton** [comment]
Perhaps eventually, but not today as it would be a breaking change

**Comment by nox** [comment]
It's not a breaking change. Things will continue to build just fine without killing computers.

**Comment by alexcrichton** [comment]
Er well I would not accept a patch which removes all the parallelism arguments. I'm fine merging a change though that avoid passing `-j` to GNU make which we know implements jobserver support.

**Comment by nox** [comment]
@alexcrichton Amended.

**Comment by nox** [comment]
@alexcrichton Could you make a new release please?

**Comment by alexcrichton** [comment]
I've now published

**Pull request merged**
